### ISSUE TITLE
"Error:(20, 0) No such property: model for class: org.gradle.plugins.ide.eclipse.EclipsePlugin"

### ISSUE THREAD

**Issue by hzsweers** [google/iosched#152] opened 2015-10-14 18:50 UTC
Happens when I try to gradle sync with the updated source. Any ideas?

**Comment by ardock** [comment] 2015-10-14 19:56
Only one result searching it in Google, try to upgrade gap to 1.9.19 or downgrade gradle < 2.3.

[Issue](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/issues/174)

[Fixed in gap 1.9.19](https://github.com/loosebazooka/gradle-appengine-plugin/commit/e20e03370b289cef07a22067412e45b5f03f37da)

The gradle wrapper included is using v. 2.2.1 and probably your local gradle is a higher version. Try this:

    ./gradlew clean assembleDebug
    ./gradlew installDebug

**Comment by hzsweers** [comment] 2015-10-14 20:00
the included gradle version is 2.2.1, or at least that's what it downloaded when I ran a clean. Seems a little frustrating that the initial release isn't even buildable. Command line gets farther before failing on not being able to find `iosched/android/debug.keystore`

**Comment by ardock** [comment] 2015-10-14 20:08
[Now you are on step 6 of the building doc, previous issue is solved using the wrapper](https://github.com/google/iosched/blob/master/doc/BUILDING.md)

**Comment by PaulRashidi** [comment] 2015-10-14 20:24
@tjohns

**Comment by tjohns** [comment] 2015-10-14 23:05
Unable to reproduce in Android Studio 1.4.

Can you please provide the following information:
- What version of Android Studio are you using?
- What platform are you on? (Windows/Mac/Linux? What version?)
- What command are you running that causes this error?
- Are you invoking Gradle from the UI, or via command line?

**Comment by eneim** [comment] 2015-10-14 23:26
I didn't face the problem too @hzsweers . What I did: checked out my old io2014 to another branch, **reset hard** my master to io2015, then rebuild from that. Android Studio 1.4 Mac OSX El Capitan, FYI.

**Comment by changbenny** [comment] 2015-10-15 04:48
I faced the same problem.
After put the debug.keystore file into project/android/ folder, I can build and install to my device(follow building tutorial step 6, 7, 8). Even though Android Studio still display the same error message: "Error:(20, 0) No such property: model for class: org.gradle.plugins.ide.eclipse.EclipsePlugin"

**Comment by lectricas** [comment] 2016-02-07 16:27
same problem here- studio 1.4

**Comment by mookrs** [comment] 2016-02-16 09:22
@lectricas Same on Android Studio 1.5. It should work after changing gap version to 1.9.30.

**Closed** 2016-03-29 22:58 UTC
Labels: 2015 Source

**Comment by naito77** [comment] 2016-05-20 11:08
Experiencing the same problem on Android Studio 2.1.1

**Comment by Keshava11** [comment] 2016-05-23 08:32
Same issue in Android Studio 2.1.1.  Please help in resolution.

**Comment by usasaradhi** [comment] 2016-08-25 10:08
Same issue in Android Studio 2.1.3
Windows 
When importing project in Android Studio using import option(eclipse, Gradle.....)
Using UI
Any solution please

**Comment by cike2056** [comment] 2016-08-31 07:52
compile 'com.android.support.test.espresso:espresso-idling-resource:2.2.1'

**Comment by nooh64** [comment] 2016-09-23 03:38
i changed 
`classpath 'com.google.appengine:gradle-appengine-plugin:1.9.18'`
to 
` classpath 'com.google.appengine:gradle-appengine-plugin:1.9.42'`

and it works!
