### ISSUE TITLE
no build

### ISSUE THREAD

**Issue by JunWeiUp** [google/iosched#201] opened 2016-06-01 03:42 UTC

**Comment by PaulRashidi** [comment] 2016-06-01 15:28
I'm going to close this because issues need to have more information about the error or problem encountered. "No build" is not sufficient context to help you.

Please re-open with your specific issue, but if the issue is related to a signing configuration you can remove it from the build.gradle dsl and sign it with your own debug key as mentioned on other issues in this repo.

**Closed by PaulRashidi** 2016-06-01 15:28 UTC
